#!/usr/bin/env python3
"""
Forward Pass — SPECIAL EDITION podcast episode maker (runs in GitHub Actions, open internet).

A special edition is a one-off episode outside the daily/weekly cadence — e.g. a full,
word-for-word reading of a paper, voiced by the same two readers as the weekly show.
Unlike the daily/weekly runners, NOTHING is generated by a model here: the episode is read
exactly from a purpose-built script that lives on Google Drive.

Each special edition is declared by a small manifest committed to this repo:

    specials/<slug>.json
    {
      "slug":        "2026-10-ai-economics",
      "title":       "The Forward Pass — Special Edition — ...",
      "script_file": "2026-10-05-special-ai-economics_special.txt",   # name on Drive
      "status":      "draft" | "published",
      "credits":     "optional HTML-safe credit line for the show notes"
    }

The script file (on Drive, in the "podcast-specials" folder under "Weekly AI Journal") uses:

    TITLE: <episode title>                (optional; manifest title wins)
    SUMMARY: <one or two sentences>        (used as the Transistor summary)
    ## CHAPTER: <chapter title>            (starts a new ID3 chapter)
    A: <text read by voice A>
    B: <text read by voice B>

Behaviour per manifest (idempotent — safe to re-run):
  * no episode with that exact title on the show yet  -> render the MP3 (two voices,
    one TTS request per turn, long turns split at sentence boundaries), embed chapters,
    upload to Transistor as a BONUS episode. It stays a DRAFT unless status == "published".
  * episode exists as a draft and status == "published" -> publish it (no re-render).
  * episode exists and FORCE=1                           -> re-render and replace its audio.
  * otherwise                                            -> nothing to do.

Env (GitHub Actions secrets/vars, shared with the daily/weekly):
  OPENAI_API_KEY, TRANSISTOR_API_KEY, TRANSISTOR_SHOW_ID, GOOGLE_SA_JSON
  TRANSISTOR_SHOW_ID_SPECIAL  optional separate show (falls back to TRANSISTOR_SHOW_ID)
  SPECIAL_DRIVE_FOLDER_ID     optional; defaults to the "podcast-specials" folder id below
  TTS_VOICE_A / TTS_VOICE_B   same voices as the weekly (defaults "marin" / "cedar")
  MANIFEST                    optional; one manifest path. Default: every specials/*.json
  FORCE                       "true" to re-render an existing episode

Deps: pip install openai google-api-python-client google-auth requests mutagen
"""
import os, sys, io, re, json, glob, html, tempfile, subprocess, shutil
import requests
from openai import OpenAI
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
from mutagen.mp3 import MP3
from mutagen.id3 import ID3, CHAP, CTOC, TIT2, CTOCFlags, ID3NoHeaderError

# ---------- config ----------
OPENAI_API_KEY     = os.environ["OPENAI_API_KEY"]
TRANSISTOR_API_KEY = os.environ["TRANSISTOR_API_KEY"]
SHOW_ID            = os.environ.get("TRANSISTOR_SHOW_ID_SPECIAL") or os.environ["TRANSISTOR_SHOW_ID"]
# Drive: "Weekly AI Journal" / "podcast-specials" (inherits the service account's Viewer share).
SPECIAL_FOLDER_ID  = os.environ.get("SPECIAL_DRIVE_FOLDER_ID") or "1aRE8nhgt1RfiBqUdZSNPnM4JbmItGAoc"
WEEKLY_FOLDER_ID   = os.environ.get("WEEKLY_DRIVE_FOLDER_ID") or "1YF23oNpM807KO-cQizSUjSDvl882J8H7"
VOICE_A            = os.environ.get("TTS_VOICE_A") or "marin"
VOICE_B            = os.environ.get("TTS_VOICE_B") or "cedar"
FORCE              = os.environ.get("FORCE", "").lower() in ("1", "true", "yes")
FEEDBACK_EMAIL     = os.environ.get("FEEDBACK_EMAIL") or "theforwardpasschannel@gmail.com"
MAX_CHARS          = 1800          # short requests keep the TTS reading faithful (API max 4096)

client = OpenAI(api_key=OPENAI_API_KEY)
TB = "https://api.transistor.fm/v1"
H = {"x-api-key": TRANSISTOR_API_KEY}

# A faithful reading, not a conversation: the words must be read exactly as written.
READ_STYLE = (
    "You are one of two narrators reading a business paper aloud, audiobook style. Read the text "
    "EXACTLY as written — do not add, skip, paraphrase or comment on any word. Clear, warm, "
    "measured delivery at a calm pace; natural emphasis on key terms, numbers and definitions; a "
    "short pause after headings. Read equations as written in words.")

# ---------- Drive ----------
def get_drive():
    creds = service_account.Credentials.from_service_account_info(
        json.loads(os.environ["GOOGLE_SA_JSON"]),
        scopes=["https://www.googleapis.com/auth/drive.readonly"])
    return build("drive", "v3", credentials=creds)

def fetch_script(drive, name):
    for folder in (SPECIAL_FOLDER_ID, WEEKLY_FOLDER_ID):
        q = f"'{folder}' in parents and trashed=false and name='{name}'"
        files = drive.files().list(q=q, orderBy="createdTime desc", pageSize=1,
                                   fields="files(id,name)").execute().get("files", [])
        if files:
            buf = io.BytesIO()
            dl = MediaIoBaseDownload(buf, drive.files().get_media(fileId=files[0]["id"]))
            done = False
            while not done:
                _, done = dl.next_chunk()
            print(f"Script: {name} ({len(buf.getvalue())} bytes, folder {folder})")
            return buf.getvalue().decode("utf-8")
    sys.exit(f"Script '{name}' not found on Drive (podcast-specials or Weekly AI Journal). "
             f"Is the folder shared (Viewer) with the service account?")

# ---------- script parsing ----------
def parse_script(text):
    """-> (title, summary, [(chapter_title, [[speaker, text], ...]), ...])"""
    title = summary = ""
    chapters, cur = [], None
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.upper().startswith("TITLE:"):
            title = line.split(":", 1)[1].strip(); continue
        if line.upper().startswith("SUMMARY:"):
            summary = line.split(":", 1)[1].strip(); continue
        m = re.match(r"^##\s*CHAPTER:\s*(.+)$", line, re.I)
        if m:
            cur = (m.group(1).strip(), []); chapters.append(cur); continue
        m = re.match(r"^([AB]):\s*(.+)$", line)
        if m:
            if cur is None:
                cur = ("Start", []); chapters.append(cur)
            cur[1].append([m.group(1), m.group(2).strip()])
        elif cur and cur[1]:
            cur[1][-1][1] += " " + line          # continuation line
    chapters = [(t, turns) for t, turns in chapters if turns]
    return title, summary, chapters

def merge_and_split(turns):
    """Merge consecutive same-speaker lines (fewer TTS seams), then split anything longer than
    MAX_CHARS at sentence boundaries. Text is never altered, only grouped."""
    merged = []
    for sp, tx in turns:
        if merged and merged[-1][0] == sp and len(merged[-1][1]) + len(tx) + 1 <= MAX_CHARS:
            merged[-1][1] += " " + tx
        else:
            merged.append([sp, tx])
    out = []
    for sp, tx in merged:
        if len(tx) <= MAX_CHARS:
            out.append([sp, tx]); continue
        buf = ""
        for s in re.split(r"(?<=[.!?])\s+", tx):
            if buf and len(buf) + len(s) + 1 > MAX_CHARS:
                out.append([sp, buf]); buf = s
            else:
                buf = f"{buf} {s}".strip()
        if buf:
            out.append([sp, buf])
    return out

# ---------- audio ----------
def synth(text, voice, path):
    for attempt in range(3):
        try:
            r = client.audio.speech.create(model="gpt-4o-mini-tts", voice=voice, input=text,
                                           instructions=READ_STYLE, response_format="mp3")
            with open(path, "wb") as fh:
                fh.write(r.content)
            return
        except Exception as e:                      # transient API errors: retry
            print(f"  TTS retry {attempt+1}: {e}")
    raise RuntimeError("TTS failed 3 times")

def dur_ms(path):
    try:
        return int(MP3(path).info.length * 1000)
    except Exception:
        return 0

def build_mp3(chapters, out_path):
    tmp = tempfile.mkdtemp(prefix="fps_")
    parts, marks, t, idx = [], [], 0, 0
    plan = [(title, merge_and_split(turns)) for title, turns in chapters]
    total = sum(len(x) for _, x in plan)
    for title, turns in plan:
        start = t
        for sp, tx in turns:
            p = os.path.join(tmp, f"t{idx:04d}.mp3"); idx += 1
            synth(tx, VOICE_A if sp == "A" else VOICE_B, p)
            parts.append(p); t += dur_ms(p)
            if idx % 10 == 0 or idx == total:
                print(f"  synth {idx}/{total}")
        marks.append([title, start, t])
    listf = os.path.join(tmp, "list.txt")
    with open(listf, "w") as fh:
        fh.writelines(f"file '{p}'\n" for p in parts)
    try:
        subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", listf, "-c", "copy",
                        out_path], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", listf,
                        "-c:a", "libmp3lame", "-b:a", "128k", out_path], check=True,
                       capture_output=True)
    real = dur_ms(out_path) or t
    marks[-1][2] = max(marks[-1][2], real)
    print(f"MP3: {out_path} ({os.path.getsize(out_path)//1024} KB, ~{round(real/60000)} min)")
    return marks

def embed_chapters(path, marks):
    try:
        tags = ID3(path)
    except ID3NoHeaderError:
        tags = ID3()
    ids = []
    for i, (title, s, e) in enumerate(marks):
        ids.append(f"chp{i}")
        tags.add(CHAP(element_id=f"chp{i}", start_time=int(s), end_time=int(e),
                      start_offset=0xFFFFFFFF, end_offset=0xFFFFFFFF,
                      sub_frames=[TIT2(encoding=3, text=[title])]))
    tags.add(CTOC(element_id="toc", flags=CTOCFlags.TOP_LEVEL | CTOCFlags.ORDERED,
                  child_element_ids=ids, sub_frames=[TIT2(encoding=3, text=["Chapters"])]))
    tags.save(path)

def ts(ms):
    s = int(ms // 1000); h, r = divmod(s, 3600); m, sec = divmod(r, 60)
    return f"{h}:{m:02d}:{sec:02d}" if h else f"{m}:{sec:02d}"

def description(summary, marks, credits):
    out = [f"<p>{html.escape(summary)}</p>"]
    if credits:
        out.append(f"<p>{credits}</p>")
    if marks:
        out.append("<p><strong>Chapters</strong></p>\n<ul>" + "".join(
            f"<li>{ts(s)} — {html.escape(t)}</li>" for t, s, e in marks) + "</ul>")
    out.append("<p>A special edition of The Forward Pass: a word-for-word reading by two "
               "AI-generated voices. No commentary has been added to the text.</p>")
    out.append(f"<p>Feedback or an AI tip to share? Write to "
               f"<a href=\"mailto:{FEEDBACK_EMAIL}\">{FEEDBACK_EMAIL}</a>.</p>")
    return "\n".join(out)

# ---------- Transistor ----------
def find_episode(title):
    page = 1
    while True:
        r = requests.get(f"{TB}/episodes", headers=H, params={
            "show_id": SHOW_ID, "pagination[page]": page, "pagination[per]": 50})
        r.raise_for_status()
        j = r.json()
        for ep in j.get("data", []):
            if (ep["attributes"].get("title") or "").strip() == title.strip():
                return ep
        if not j.get("data") or page >= int(j.get("meta", {}).get("totalPages", page)):
            return None
        page += 1

def upload_audio(mp3_path):
    au = requests.get(f"{TB}/episodes/authorize_upload", headers=H,
                      params={"filename": os.path.basename(mp3_path)})
    au.raise_for_status()
    a = au.json()["data"]["attributes"]
    with open(mp3_path, "rb") as fh:
        requests.put(a["upload_url"], data=fh,
                     headers={"Content-Type": "audio/mpeg"}).raise_for_status()
    return a["audio_url"]

def create_episode(title, summary, desc, audio_url):
    data = {"episode[show_id]": SHOW_ID, "episode[title]": title,
            "episode[summary]": summary, "episode[description]": desc,
            "episode[audio_url]": audio_url, "episode[type]": "bonus"}
    r = requests.post(f"{TB}/episodes", headers=H, data=data)
    if r.status_code >= 400:                      # fall back if 'type' is rejected
        print(f"Create with type=bonus failed ({r.status_code}: {r.text[:200]}); retrying as full.")
        data.pop("episode[type]")
        r = requests.post(f"{TB}/episodes", headers=H, data=data)
    r.raise_for_status()
    return r.json()["data"]["id"]

def publish(eid):
    requests.patch(f"{TB}/episodes/{eid}/publish", headers=H,
                   data={"episode[status]": "published"}).raise_for_status()
    print(f"PUBLISHED episode {eid} — it will reach Spotify via the RSS feed.")

# ---------- main ----------
def run(manifest_path, drive):
    m = json.load(open(manifest_path))
    title, want = m["title"], (m.get("status") or "draft").lower()
    print(f"\n=== {m.get('slug', manifest_path)} — wanted status: {want}")
    ep = find_episode(title)
    if ep and not FORCE:
        state = ep["attributes"].get("status")
        print(f"Episode exists: id {ep['id']}, status {state}")
        if want == "published" and state != "published":
            publish(ep["id"])
        else:
            print("Nothing to do.")
        return
    raw = fetch_script(drive, m["script_file"])
    _, summary, chapters = parse_script(raw)
    words = sum(len(t.split()) for _, turns in chapters for _, t in turns)
    print(f"{len(chapters)} chapters, {sum(len(t) for _, t in chapters)} turns, "
          f"{words} words (~{round(words/150)} min)")
    if words < 200:
        sys.exit("Script looks empty/broken — aborting.")
    out_dir = os.environ.get("OUT_DIR") or tempfile.gettempdir()
    mp3 = os.path.join(out_dir, f"forwardpass_special_{m.get('slug', 'episode')}.mp3")
    marks = build_mp3(chapters, mp3)
    embed_chapters(mp3, marks)
    desc = description(summary or m.get("summary", ""), marks, m.get("credits", ""))
    audio_url = upload_audio(mp3)
    if ep:   # FORCE re-render: replace audio + notes on the existing episode
        requests.patch(f"{TB}/episodes/{ep['id']}", headers=H, data={
            "episode[audio_url]": audio_url, "episode[description]": desc,
            "episode[summary]": summary}).raise_for_status()
        eid = ep["id"]; print(f"Replaced audio on episode {eid}.")
    else:
        eid = create_episode(title, summary, desc, audio_url)
        print(f"Created DRAFT episode {eid}: {title}")
    if want == "published":
        publish(eid)
    else:
        print("Left as DRAFT. Listen in the Transistor dashboard; set \"status\": \"published\" "
              "in the manifest and push to release it to Spotify.")

if __name__ == "__main__":
    paths = [os.environ["MANIFEST"]] if os.environ.get("MANIFEST") else sorted(glob.glob("specials/*.json"))
    if not paths:
        sys.exit("No special-edition manifests found.")
    drive = get_drive()
    for p in paths:
        run(p, drive)
    print("Done.")
